// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication.proto

/*
Package authentication is a generated protocol buffer package.

It is generated from these files:
	authentication.proto

It has these top-level messages:
	ClientResponseEncrypted
	LoginCredentials
	FingerprintResponseUnion
	FingerprintGrainResponse
	FingerprintHmacRipemdResponse
	PeerTicketUnion
	PeerTicketPublicKey
	PeerTicketOld
	SystemInfo
	LibspotifyAppKey
	ClientInfo
	ClientInfoFacebook
	APWelcome
	AccountInfo
	AccountInfoSpotify
	AccountInfoFacebook
*/
package authentication

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthenticationType int32

const (
	AuthenticationType_AUTHENTICATION_USER_PASS                   AuthenticationType = 0
	AuthenticationType_AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS  AuthenticationType = 1
	AuthenticationType_AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS AuthenticationType = 2
	AuthenticationType_AUTHENTICATION_SPOTIFY_TOKEN               AuthenticationType = 3
	AuthenticationType_AUTHENTICATION_FACEBOOK_TOKEN              AuthenticationType = 4
)

var AuthenticationType_name = map[int32]string{
	0: "AUTHENTICATION_USER_PASS",
	1: "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",
	2: "AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS",
	3: "AUTHENTICATION_SPOTIFY_TOKEN",
	4: "AUTHENTICATION_FACEBOOK_TOKEN",
}
var AuthenticationType_value = map[string]int32{
	"AUTHENTICATION_USER_PASS":                   0,
	"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS":  1,
	"AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS": 2,
	"AUTHENTICATION_SPOTIFY_TOKEN":               3,
	"AUTHENTICATION_FACEBOOK_TOKEN":              4,
}

func (x AuthenticationType) Enum() *AuthenticationType {
	p := new(AuthenticationType)
	*p = x
	return p
}
func (x AuthenticationType) String() string {
	return proto.EnumName(AuthenticationType_name, int32(x))
}
func (x *AuthenticationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AuthenticationType_value, data, "AuthenticationType")
	if err != nil {
		return err
	}
	*x = AuthenticationType(value)
	return nil
}
func (AuthenticationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AccountCreation int32

const (
	AccountCreation_ACCOUNT_CREATION_ALWAYS_PROMPT AccountCreation = 1
	AccountCreation_ACCOUNT_CREATION_ALWAYS_CREATE AccountCreation = 3
)

var AccountCreation_name = map[int32]string{
	1: "ACCOUNT_CREATION_ALWAYS_PROMPT",
	3: "ACCOUNT_CREATION_ALWAYS_CREATE",
}
var AccountCreation_value = map[string]int32{
	"ACCOUNT_CREATION_ALWAYS_PROMPT": 1,
	"ACCOUNT_CREATION_ALWAYS_CREATE": 3,
}

func (x AccountCreation) Enum() *AccountCreation {
	p := new(AccountCreation)
	*p = x
	return p
}
func (x AccountCreation) String() string {
	return proto.EnumName(AccountCreation_name, int32(x))
}
func (x *AccountCreation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AccountCreation_value, data, "AccountCreation")
	if err != nil {
		return err
	}
	*x = AccountCreation(value)
	return nil
}
func (AccountCreation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CpuFamily int32

const (
	CpuFamily_CPU_UNKNOWN  CpuFamily = 0
	CpuFamily_CPU_X86      CpuFamily = 1
	CpuFamily_CPU_X86_64   CpuFamily = 2
	CpuFamily_CPU_PPC      CpuFamily = 3
	CpuFamily_CPU_PPC_64   CpuFamily = 4
	CpuFamily_CPU_ARM      CpuFamily = 5
	CpuFamily_CPU_IA64     CpuFamily = 6
	CpuFamily_CPU_SH       CpuFamily = 7
	CpuFamily_CPU_MIPS     CpuFamily = 8
	CpuFamily_CPU_BLACKFIN CpuFamily = 9
)

var CpuFamily_name = map[int32]string{
	0: "CPU_UNKNOWN",
	1: "CPU_X86",
	2: "CPU_X86_64",
	3: "CPU_PPC",
	4: "CPU_PPC_64",
	5: "CPU_ARM",
	6: "CPU_IA64",
	7: "CPU_SH",
	8: "CPU_MIPS",
	9: "CPU_BLACKFIN",
}
var CpuFamily_value = map[string]int32{
	"CPU_UNKNOWN":  0,
	"CPU_X86":      1,
	"CPU_X86_64":   2,
	"CPU_PPC":      3,
	"CPU_PPC_64":   4,
	"CPU_ARM":      5,
	"CPU_IA64":     6,
	"CPU_SH":       7,
	"CPU_MIPS":     8,
	"CPU_BLACKFIN": 9,
}

func (x CpuFamily) Enum() *CpuFamily {
	p := new(CpuFamily)
	*p = x
	return p
}
func (x CpuFamily) String() string {
	return proto.EnumName(CpuFamily_name, int32(x))
}
func (x *CpuFamily) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CpuFamily_value, data, "CpuFamily")
	if err != nil {
		return err
	}
	*x = CpuFamily(value)
	return nil
}
func (CpuFamily) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Brand int32

const (
	Brand_BRAND_UNBRANDED Brand = 0
	Brand_BRAND_INQ       Brand = 1
	Brand_BRAND_HTC       Brand = 2
	Brand_BRAND_NOKIA     Brand = 3
)

var Brand_name = map[int32]string{
	0: "BRAND_UNBRANDED",
	1: "BRAND_INQ",
	2: "BRAND_HTC",
	3: "BRAND_NOKIA",
}
var Brand_value = map[string]int32{
	"BRAND_UNBRANDED": 0,
	"BRAND_INQ":       1,
	"BRAND_HTC":       2,
	"BRAND_NOKIA":     3,
}

func (x Brand) Enum() *Brand {
	p := new(Brand)
	*p = x
	return p
}
func (x Brand) String() string {
	return proto.EnumName(Brand_name, int32(x))
}
func (x *Brand) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Brand_value, data, "Brand")
	if err != nil {
		return err
	}
	*x = Brand(value)
	return nil
}
func (Brand) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Os int32

const (
	Os_OS_UNKNOWN    Os = 0
	Os_OS_WINDOWS    Os = 1
	Os_OS_OSX        Os = 2
	Os_OS_IPHONE     Os = 3
	Os_OS_S60        Os = 4
	Os_OS_LINUX      Os = 5
	Os_OS_WINDOWS_CE Os = 6
	Os_OS_ANDROID    Os = 7
	Os_OS_PALM       Os = 8
	Os_OS_FREEBSD    Os = 9
	Os_OS_BLACKBERRY Os = 10
	Os_OS_SONOS      Os = 11
	Os_OS_LOGITECH   Os = 12
	Os_OS_WP7        Os = 13
	Os_OS_ONKYO      Os = 14
	Os_OS_PHILIPS    Os = 15
	Os_OS_WD         Os = 16
	Os_OS_VOLVO      Os = 17
	Os_OS_TIVO       Os = 18
	Os_OS_AWOX       Os = 19
	Os_OS_MEEGO      Os = 20
	Os_OS_QNXNTO     Os = 21
	Os_OS_BCO        Os = 22
)

var Os_name = map[int32]string{
	0:  "OS_UNKNOWN",
	1:  "OS_WINDOWS",
	2:  "OS_OSX",
	3:  "OS_IPHONE",
	4:  "OS_S60",
	5:  "OS_LINUX",
	6:  "OS_WINDOWS_CE",
	7:  "OS_ANDROID",
	8:  "OS_PALM",
	9:  "OS_FREEBSD",
	10: "OS_BLACKBERRY",
	11: "OS_SONOS",
	12: "OS_LOGITECH",
	13: "OS_WP7",
	14: "OS_ONKYO",
	15: "OS_PHILIPS",
	16: "OS_WD",
	17: "OS_VOLVO",
	18: "OS_TIVO",
	19: "OS_AWOX",
	20: "OS_MEEGO",
	21: "OS_QNXNTO",
	22: "OS_BCO",
}
var Os_value = map[string]int32{
	"OS_UNKNOWN":    0,
	"OS_WINDOWS":    1,
	"OS_OSX":        2,
	"OS_IPHONE":     3,
	"OS_S60":        4,
	"OS_LINUX":      5,
	"OS_WINDOWS_CE": 6,
	"OS_ANDROID":    7,
	"OS_PALM":       8,
	"OS_FREEBSD":    9,
	"OS_BLACKBERRY": 10,
	"OS_SONOS":      11,
	"OS_LOGITECH":   12,
	"OS_WP7":        13,
	"OS_ONKYO":      14,
	"OS_PHILIPS":    15,
	"OS_WD":         16,
	"OS_VOLVO":      17,
	"OS_TIVO":       18,
	"OS_AWOX":       19,
	"OS_MEEGO":      20,
	"OS_QNXNTO":     21,
	"OS_BCO":        22,
}

func (x Os) Enum() *Os {
	p := new(Os)
	*p = x
	return p
}
func (x Os) String() string {
	return proto.EnumName(Os_name, int32(x))
}
func (x *Os) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Os_value, data, "Os")
	if err != nil {
		return err
	}
	*x = Os(value)
	return nil
}
func (Os) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type AccountType int32

const (
	AccountType_Spotify  AccountType = 0
	AccountType_Facebook AccountType = 1
)

var AccountType_name = map[int32]string{
	0: "Spotify",
	1: "Facebook",
}
var AccountType_value = map[string]int32{
	"Spotify":  0,
	"Facebook": 1,
}

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}
func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (x *AccountType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AccountType_value, data, "AccountType")
	if err != nil {
		return err
	}
	*x = AccountType(value)
	return nil
}
func (AccountType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ClientResponseEncrypted struct {
	LoginCredentials    *LoginCredentials         `protobuf:"bytes,10,req,name=login_credentials,json=loginCredentials" json:"login_credentials,omitempty"`
	AccountCreation     *AccountCreation          `protobuf:"varint,20,opt,name=account_creation,json=accountCreation,enum=AccountCreation" json:"account_creation,omitempty"`
	FingerprintResponse *FingerprintResponseUnion `protobuf:"bytes,30,opt,name=fingerprint_response,json=fingerprintResponse" json:"fingerprint_response,omitempty"`
	PeerTicket          *PeerTicketUnion          `protobuf:"bytes,40,opt,name=peer_ticket,json=peerTicket" json:"peer_ticket,omitempty"`
	SystemInfo          *SystemInfo               `protobuf:"bytes,50,req,name=system_info,json=systemInfo" json:"system_info,omitempty"`
	PlatformModel       *string                   `protobuf:"bytes,60,opt,name=platform_model,json=platformModel" json:"platform_model,omitempty"`
	VersionString       *string                   `protobuf:"bytes,70,opt,name=version_string,json=versionString" json:"version_string,omitempty"`
	Appkey              *LibspotifyAppKey         `protobuf:"bytes,80,opt,name=appkey" json:"appkey,omitempty"`
	ClientInfo          *ClientInfo               `protobuf:"bytes,90,opt,name=client_info,json=clientInfo" json:"client_info,omitempty"`
	XXX_unrecognized    []byte                    `json:"-"`
}

func (m *ClientResponseEncrypted) Reset()                    { *m = ClientResponseEncrypted{} }
func (m *ClientResponseEncrypted) String() string            { return proto.CompactTextString(m) }
func (*ClientResponseEncrypted) ProtoMessage()               {}
func (*ClientResponseEncrypted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClientResponseEncrypted) GetLoginCredentials() *LoginCredentials {
	if m != nil {
		return m.LoginCredentials
	}
	return nil
}

func (m *ClientResponseEncrypted) GetAccountCreation() AccountCreation {
	if m != nil && m.AccountCreation != nil {
		return *m.AccountCreation
	}
	return AccountCreation_ACCOUNT_CREATION_ALWAYS_PROMPT
}

func (m *ClientResponseEncrypted) GetFingerprintResponse() *FingerprintResponseUnion {
	if m != nil {
		return m.FingerprintResponse
	}
	return nil
}

func (m *ClientResponseEncrypted) GetPeerTicket() *PeerTicketUnion {
	if m != nil {
		return m.PeerTicket
	}
	return nil
}

func (m *ClientResponseEncrypted) GetSystemInfo() *SystemInfo {
	if m != nil {
		return m.SystemInfo
	}
	return nil
}

func (m *ClientResponseEncrypted) GetPlatformModel() string {
	if m != nil && m.PlatformModel != nil {
		return *m.PlatformModel
	}
	return ""
}

func (m *ClientResponseEncrypted) GetVersionString() string {
	if m != nil && m.VersionString != nil {
		return *m.VersionString
	}
	return ""
}

func (m *ClientResponseEncrypted) GetAppkey() *LibspotifyAppKey {
	if m != nil {
		return m.Appkey
	}
	return nil
}

func (m *ClientResponseEncrypted) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type LoginCredentials struct {
	Username         *string             `protobuf:"bytes,10,opt,name=username" json:"username,omitempty"`
	Typ              *AuthenticationType `protobuf:"varint,20,req,name=typ,enum=AuthenticationType" json:"typ,omitempty"`
	AuthData         []byte              `protobuf:"bytes,30,opt,name=auth_data,json=authData" json:"auth_data,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *LoginCredentials) Reset()                    { *m = LoginCredentials{} }
func (m *LoginCredentials) String() string            { return proto.CompactTextString(m) }
func (*LoginCredentials) ProtoMessage()               {}
func (*LoginCredentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginCredentials) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *LoginCredentials) GetTyp() AuthenticationType {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return AuthenticationType_AUTHENTICATION_USER_PASS
}

func (m *LoginCredentials) GetAuthData() []byte {
	if m != nil {
		return m.AuthData
	}
	return nil
}

type FingerprintResponseUnion struct {
	Grain            *FingerprintGrainResponse      `protobuf:"bytes,10,opt,name=grain" json:"grain,omitempty"`
	HmacRipemd       *FingerprintHmacRipemdResponse `protobuf:"bytes,20,opt,name=hmac_ripemd,json=hmacRipemd" json:"hmac_ripemd,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *FingerprintResponseUnion) Reset()                    { *m = FingerprintResponseUnion{} }
func (m *FingerprintResponseUnion) String() string            { return proto.CompactTextString(m) }
func (*FingerprintResponseUnion) ProtoMessage()               {}
func (*FingerprintResponseUnion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FingerprintResponseUnion) GetGrain() *FingerprintGrainResponse {
	if m != nil {
		return m.Grain
	}
	return nil
}

func (m *FingerprintResponseUnion) GetHmacRipemd() *FingerprintHmacRipemdResponse {
	if m != nil {
		return m.HmacRipemd
	}
	return nil
}

type FingerprintGrainResponse struct {
	EncryptedKey     []byte `protobuf:"bytes,10,req,name=encrypted_key,json=encryptedKey" json:"encrypted_key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FingerprintGrainResponse) Reset()                    { *m = FingerprintGrainResponse{} }
func (m *FingerprintGrainResponse) String() string            { return proto.CompactTextString(m) }
func (*FingerprintGrainResponse) ProtoMessage()               {}
func (*FingerprintGrainResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FingerprintGrainResponse) GetEncryptedKey() []byte {
	if m != nil {
		return m.EncryptedKey
	}
	return nil
}

type FingerprintHmacRipemdResponse struct {
	Hmac             []byte `protobuf:"bytes,10,req,name=hmac" json:"hmac,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FingerprintHmacRipemdResponse) Reset()                    { *m = FingerprintHmacRipemdResponse{} }
func (m *FingerprintHmacRipemdResponse) String() string            { return proto.CompactTextString(m) }
func (*FingerprintHmacRipemdResponse) ProtoMessage()               {}
func (*FingerprintHmacRipemdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FingerprintHmacRipemdResponse) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

type PeerTicketUnion struct {
	PublicKey        *PeerTicketPublicKey `protobuf:"bytes,10,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	OldTicket        *PeerTicketOld       `protobuf:"bytes,20,opt,name=old_ticket,json=oldTicket" json:"old_ticket,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *PeerTicketUnion) Reset()                    { *m = PeerTicketUnion{} }
func (m *PeerTicketUnion) String() string            { return proto.CompactTextString(m) }
func (*PeerTicketUnion) ProtoMessage()               {}
func (*PeerTicketUnion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PeerTicketUnion) GetPublicKey() *PeerTicketPublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PeerTicketUnion) GetOldTicket() *PeerTicketOld {
	if m != nil {
		return m.OldTicket
	}
	return nil
}

type PeerTicketPublicKey struct {
	PublicKey        []byte `protobuf:"bytes,10,req,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PeerTicketPublicKey) Reset()                    { *m = PeerTicketPublicKey{} }
func (m *PeerTicketPublicKey) String() string            { return proto.CompactTextString(m) }
func (*PeerTicketPublicKey) ProtoMessage()               {}
func (*PeerTicketPublicKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PeerTicketPublicKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type PeerTicketOld struct {
	PeerTicket          []byte `protobuf:"bytes,10,req,name=peer_ticket,json=peerTicket" json:"peer_ticket,omitempty"`
	PeerTicketSignature []byte `protobuf:"bytes,20,req,name=peer_ticket_signature,json=peerTicketSignature" json:"peer_ticket_signature,omitempty"`
	XXX_unrecognized    []byte `json:"-"`
}

func (m *PeerTicketOld) Reset()                    { *m = PeerTicketOld{} }
func (m *PeerTicketOld) String() string            { return proto.CompactTextString(m) }
func (*PeerTicketOld) ProtoMessage()               {}
func (*PeerTicketOld) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PeerTicketOld) GetPeerTicket() []byte {
	if m != nil {
		return m.PeerTicket
	}
	return nil
}

func (m *PeerTicketOld) GetPeerTicketSignature() []byte {
	if m != nil {
		return m.PeerTicketSignature
	}
	return nil
}

type SystemInfo struct {
	CpuFamily               *CpuFamily `protobuf:"varint,10,req,name=cpu_family,json=cpuFamily,enum=CpuFamily" json:"cpu_family,omitempty"`
	CpuSubtype              *uint32    `protobuf:"varint,20,opt,name=cpu_subtype,json=cpuSubtype" json:"cpu_subtype,omitempty"`
	CpuExt                  *uint32    `protobuf:"varint,30,opt,name=cpu_ext,json=cpuExt" json:"cpu_ext,omitempty"`
	Brand                   *Brand     `protobuf:"varint,40,opt,name=brand,enum=Brand" json:"brand,omitempty"`
	BrandFlags              *uint32    `protobuf:"varint,50,opt,name=brand_flags,json=brandFlags" json:"brand_flags,omitempty"`
	Os                      *Os        `protobuf:"varint,60,req,name=os,enum=Os" json:"os,omitempty"`
	OsVersion               *uint32    `protobuf:"varint,70,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	OsExt                   *uint32    `protobuf:"varint,80,opt,name=os_ext,json=osExt" json:"os_ext,omitempty"`
	SystemInformationString *string    `protobuf:"bytes,90,opt,name=system_information_string,json=systemInformationString" json:"system_information_string,omitempty"`
	DeviceId                *string    `protobuf:"bytes,100,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	XXX_unrecognized        []byte     `json:"-"`
}

func (m *SystemInfo) Reset()                    { *m = SystemInfo{} }
func (m *SystemInfo) String() string            { return proto.CompactTextString(m) }
func (*SystemInfo) ProtoMessage()               {}
func (*SystemInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SystemInfo) GetCpuFamily() CpuFamily {
	if m != nil && m.CpuFamily != nil {
		return *m.CpuFamily
	}
	return CpuFamily_CPU_UNKNOWN
}

func (m *SystemInfo) GetCpuSubtype() uint32 {
	if m != nil && m.CpuSubtype != nil {
		return *m.CpuSubtype
	}
	return 0
}

func (m *SystemInfo) GetCpuExt() uint32 {
	if m != nil && m.CpuExt != nil {
		return *m.CpuExt
	}
	return 0
}

func (m *SystemInfo) GetBrand() Brand {
	if m != nil && m.Brand != nil {
		return *m.Brand
	}
	return Brand_BRAND_UNBRANDED
}

func (m *SystemInfo) GetBrandFlags() uint32 {
	if m != nil && m.BrandFlags != nil {
		return *m.BrandFlags
	}
	return 0
}

func (m *SystemInfo) GetOs() Os {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return Os_OS_UNKNOWN
}

func (m *SystemInfo) GetOsVersion() uint32 {
	if m != nil && m.OsVersion != nil {
		return *m.OsVersion
	}
	return 0
}

func (m *SystemInfo) GetOsExt() uint32 {
	if m != nil && m.OsExt != nil {
		return *m.OsExt
	}
	return 0
}

func (m *SystemInfo) GetSystemInformationString() string {
	if m != nil && m.SystemInformationString != nil {
		return *m.SystemInformationString
	}
	return ""
}

func (m *SystemInfo) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

type LibspotifyAppKey struct {
	Version          *uint32 `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Devkey           []byte  `protobuf:"bytes,2,req,name=devkey" json:"devkey,omitempty"`
	Signature        []byte  `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	Useragent        *string `protobuf:"bytes,4,req,name=useragent" json:"useragent,omitempty"`
	CallbackHash     []byte  `protobuf:"bytes,5,req,name=callback_hash,json=callbackHash" json:"callback_hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LibspotifyAppKey) Reset()                    { *m = LibspotifyAppKey{} }
func (m *LibspotifyAppKey) String() string            { return proto.CompactTextString(m) }
func (*LibspotifyAppKey) ProtoMessage()               {}
func (*LibspotifyAppKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LibspotifyAppKey) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *LibspotifyAppKey) GetDevkey() []byte {
	if m != nil {
		return m.Devkey
	}
	return nil
}

func (m *LibspotifyAppKey) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *LibspotifyAppKey) GetUseragent() string {
	if m != nil && m.Useragent != nil {
		return *m.Useragent
	}
	return ""
}

func (m *LibspotifyAppKey) GetCallbackHash() []byte {
	if m != nil {
		return m.CallbackHash
	}
	return nil
}

type ClientInfo struct {
	Limited          *bool               `protobuf:"varint,1,opt,name=limited" json:"limited,omitempty"`
	Fb               *ClientInfoFacebook `protobuf:"bytes,2,opt,name=fb" json:"fb,omitempty"`
	Language         *string             `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ClientInfo) Reset()                    { *m = ClientInfo{} }
func (m *ClientInfo) String() string            { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()               {}
func (*ClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ClientInfo) GetLimited() bool {
	if m != nil && m.Limited != nil {
		return *m.Limited
	}
	return false
}

func (m *ClientInfo) GetFb() *ClientInfoFacebook {
	if m != nil {
		return m.Fb
	}
	return nil
}

func (m *ClientInfo) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

type ClientInfoFacebook struct {
	MachineId        *string `protobuf:"bytes,1,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ClientInfoFacebook) Reset()                    { *m = ClientInfoFacebook{} }
func (m *ClientInfoFacebook) String() string            { return proto.CompactTextString(m) }
func (*ClientInfoFacebook) ProtoMessage()               {}
func (*ClientInfoFacebook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ClientInfoFacebook) GetMachineId() string {
	if m != nil && m.MachineId != nil {
		return *m.MachineId
	}
	return ""
}

type APWelcome struct {
	CanonicalUsername           *string              `protobuf:"bytes,10,req,name=canonical_username,json=canonicalUsername" json:"canonical_username,omitempty"`
	AccountTypeLoggedIn         *AccountType         `protobuf:"varint,20,req,name=account_type_logged_in,json=accountTypeLoggedIn,enum=AccountType" json:"account_type_logged_in,omitempty"`
	CredentialsTypeLoggedIn     *AccountType         `protobuf:"varint,25,req,name=credentials_type_logged_in,json=credentialsTypeLoggedIn,enum=AccountType" json:"credentials_type_logged_in,omitempty"`
	ReusableAuthCredentialsType *AuthenticationType  `protobuf:"varint,30,req,name=reusable_auth_credentials_type,json=reusableAuthCredentialsType,enum=AuthenticationType" json:"reusable_auth_credentials_type,omitempty"`
	ReusableAuthCredentials     []byte               `protobuf:"bytes,40,req,name=reusable_auth_credentials,json=reusableAuthCredentials" json:"reusable_auth_credentials,omitempty"`
	LfsSecret                   []byte               `protobuf:"bytes,50,opt,name=lfs_secret,json=lfsSecret" json:"lfs_secret,omitempty"`
	AccountInfo                 *AccountInfo         `protobuf:"bytes,60,opt,name=account_info,json=accountInfo" json:"account_info,omitempty"`
	Fb                          *AccountInfoFacebook `protobuf:"bytes,70,opt,name=fb" json:"fb,omitempty"`
	XXX_unrecognized            []byte               `json:"-"`
}

func (m *APWelcome) Reset()                    { *m = APWelcome{} }
func (m *APWelcome) String() string            { return proto.CompactTextString(m) }
func (*APWelcome) ProtoMessage()               {}
func (*APWelcome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *APWelcome) GetCanonicalUsername() string {
	if m != nil && m.CanonicalUsername != nil {
		return *m.CanonicalUsername
	}
	return ""
}

func (m *APWelcome) GetAccountTypeLoggedIn() AccountType {
	if m != nil && m.AccountTypeLoggedIn != nil {
		return *m.AccountTypeLoggedIn
	}
	return AccountType_Spotify
}

func (m *APWelcome) GetCredentialsTypeLoggedIn() AccountType {
	if m != nil && m.CredentialsTypeLoggedIn != nil {
		return *m.CredentialsTypeLoggedIn
	}
	return AccountType_Spotify
}

func (m *APWelcome) GetReusableAuthCredentialsType() AuthenticationType {
	if m != nil && m.ReusableAuthCredentialsType != nil {
		return *m.ReusableAuthCredentialsType
	}
	return AuthenticationType_AUTHENTICATION_USER_PASS
}

func (m *APWelcome) GetReusableAuthCredentials() []byte {
	if m != nil {
		return m.ReusableAuthCredentials
	}
	return nil
}

func (m *APWelcome) GetLfsSecret() []byte {
	if m != nil {
		return m.LfsSecret
	}
	return nil
}

func (m *APWelcome) GetAccountInfo() *AccountInfo {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

func (m *APWelcome) GetFb() *AccountInfoFacebook {
	if m != nil {
		return m.Fb
	}
	return nil
}

type AccountInfo struct {
	Spotify          *AccountInfoSpotify  `protobuf:"bytes,1,opt,name=spotify" json:"spotify,omitempty"`
	Facebook         *AccountInfoFacebook `protobuf:"bytes,2,opt,name=facebook" json:"facebook,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *AccountInfo) Reset()                    { *m = AccountInfo{} }
func (m *AccountInfo) String() string            { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()               {}
func (*AccountInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *AccountInfo) GetSpotify() *AccountInfoSpotify {
	if m != nil {
		return m.Spotify
	}
	return nil
}

func (m *AccountInfo) GetFacebook() *AccountInfoFacebook {
	if m != nil {
		return m.Facebook
	}
	return nil
}

type AccountInfoSpotify struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AccountInfoSpotify) Reset()                    { *m = AccountInfoSpotify{} }
func (m *AccountInfoSpotify) String() string            { return proto.CompactTextString(m) }
func (*AccountInfoSpotify) ProtoMessage()               {}
func (*AccountInfoSpotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type AccountInfoFacebook struct {
	AccessToken      *string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	MachineId        *string `protobuf:"bytes,2,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccountInfoFacebook) Reset()                    { *m = AccountInfoFacebook{} }
func (m *AccountInfoFacebook) String() string            { return proto.CompactTextString(m) }
func (*AccountInfoFacebook) ProtoMessage()               {}
func (*AccountInfoFacebook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *AccountInfoFacebook) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *AccountInfoFacebook) GetMachineId() string {
	if m != nil && m.MachineId != nil {
		return *m.MachineId
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientResponseEncrypted)(nil), "ClientResponseEncrypted")
	proto.RegisterType((*LoginCredentials)(nil), "LoginCredentials")
	proto.RegisterType((*FingerprintResponseUnion)(nil), "FingerprintResponseUnion")
	proto.RegisterType((*FingerprintGrainResponse)(nil), "FingerprintGrainResponse")
	proto.RegisterType((*FingerprintHmacRipemdResponse)(nil), "FingerprintHmacRipemdResponse")
	proto.RegisterType((*PeerTicketUnion)(nil), "PeerTicketUnion")
	proto.RegisterType((*PeerTicketPublicKey)(nil), "PeerTicketPublicKey")
	proto.RegisterType((*PeerTicketOld)(nil), "PeerTicketOld")
	proto.RegisterType((*SystemInfo)(nil), "SystemInfo")
	proto.RegisterType((*LibspotifyAppKey)(nil), "LibspotifyAppKey")
	proto.RegisterType((*ClientInfo)(nil), "ClientInfo")
	proto.RegisterType((*ClientInfoFacebook)(nil), "ClientInfoFacebook")
	proto.RegisterType((*APWelcome)(nil), "APWelcome")
	proto.RegisterType((*AccountInfo)(nil), "AccountInfo")
	proto.RegisterType((*AccountInfoSpotify)(nil), "AccountInfoSpotify")
	proto.RegisterType((*AccountInfoFacebook)(nil), "AccountInfoFacebook")
	proto.RegisterEnum("AuthenticationType", AuthenticationType_name, AuthenticationType_value)
	proto.RegisterEnum("AccountCreation", AccountCreation_name, AccountCreation_value)
	proto.RegisterEnum("CpuFamily", CpuFamily_name, CpuFamily_value)
	proto.RegisterEnum("Brand", Brand_name, Brand_value)
	proto.RegisterEnum("Os", Os_name, Os_value)
	proto.RegisterEnum("AccountType", AccountType_name, AccountType_value)
}

func init() { proto.RegisterFile("authentication.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xeb, 0x6e, 0xdb, 0xc8,
	0x15, 0x8e, 0x28, 0xdf, 0x74, 0x24, 0xd9, 0xe3, 0x91, 0x13, 0x33, 0x9b, 0xc4, 0xf5, 0x6a, 0xbb,
	0x80, 0x62, 0x34, 0xda, 0xad, 0x12, 0xa4, 0x45, 0x1b, 0x74, 0x41, 0x53, 0x54, 0x4c, 0x48, 0x26,
	0xb9, 0x43, 0x29, 0xb6, 0xf7, 0x0f, 0x41, 0x91, 0x23, 0x99, 0x30, 0x45, 0x12, 0x24, 0x15, 0xac,
	0xde, 0xa1, 0xaf, 0xd0, 0x9f, 0x7d, 0xa0, 0x02, 0x8b, 0x3e, 0x45, 0x1f, 0xa2, 0x98, 0x21, 0xa9,
	0x5b, 0x9c, 0xfd, 0x25, 0x9e, 0xef, 0x3b, 0xb7, 0x99, 0x73, 0x19, 0xc1, 0x89, 0x3d, 0x4f, 0xef,
	0x69, 0x90, 0x7a, 0x8e, 0x9d, 0x7a, 0x61, 0xd0, 0x8e, 0xe2, 0x30, 0x0d, 0x9b, 0xff, 0x2b, 0xc3,
	0xa9, 0xec, 0x7b, 0x34, 0x48, 0x09, 0x4d, 0xa2, 0x30, 0x48, 0xa8, 0x12, 0x38, 0xf1, 0x22, 0x4a,
	0xa9, 0x8b, 0xff, 0x01, 0xc7, 0x7e, 0x38, 0xf5, 0x02, 0xcb, 0x89, 0xa9, 0xcb, 0x2c, 0x6d, 0x3f,
	0x11, 0xe1, 0x5c, 0x68, 0x55, 0x3b, 0xc7, 0xed, 0x01, 0x63, 0xe4, 0x15, 0x41, 0x90, 0xbf, 0x85,
	0xe0, 0xbf, 0x03, 0xb2, 0x1d, 0x27, 0x9c, 0x07, 0x29, 0xf3, 0xc0, 0xa3, 0x8a, 0x27, 0xe7, 0xa5,
	0xd6, 0x61, 0x07, 0xb5, 0xa5, 0x8c, 0x90, 0x73, 0x9c, 0x1c, 0xd9, 0x9b, 0x00, 0x1e, 0xc0, 0xc9,
	0xc4, 0x0b, 0xa6, 0x34, 0x8e, 0x62, 0x2f, 0x48, 0xad, 0x38, 0xcf, 0x4e, 0x3c, 0x3b, 0x2f, 0xb5,
	0xaa, 0x9d, 0xe7, 0xed, 0xde, 0x8a, 0x2c, 0x32, 0x1f, 0x05, 0xcc, 0x53, 0x63, 0xf2, 0x25, 0x83,
	0xff, 0x0c, 0xd5, 0x88, 0xd2, 0xd8, 0x4a, 0x3d, 0xe7, 0x81, 0xa6, 0x62, 0x8b, 0x3b, 0x41, 0x6d,
	0x83, 0xd2, 0x78, 0xc8, 0xa1, 0xcc, 0x16, 0xa2, 0x25, 0x80, 0xff, 0x04, 0xd5, 0x64, 0x91, 0xa4,
	0x74, 0x66, 0x79, 0xc1, 0x24, 0x14, 0x3b, 0xfc, 0xdc, 0xd5, 0xb6, 0xc9, 0x31, 0x35, 0x98, 0x84,
	0x04, 0x92, 0xe5, 0x37, 0xfe, 0x1e, 0x0e, 0x23, 0xdf, 0x4e, 0x27, 0x61, 0x3c, 0xb3, 0x66, 0xa1,
	0x4b, 0x7d, 0xf1, 0xc3, 0x79, 0xa9, 0x55, 0x21, 0xf5, 0x02, 0xbd, 0x66, 0x20, 0x53, 0xfb, 0x4c,
	0xe3, 0xc4, 0x0b, 0x03, 0x2b, 0x49, 0x63, 0x2f, 0x98, 0x8a, 0xbd, 0x4c, 0x2d, 0x47, 0x4d, 0x0e,
	0xe2, 0xd7, 0xb0, 0x67, 0x47, 0xd1, 0x03, 0x5d, 0x88, 0x06, 0xcf, 0xf4, 0xb8, 0x3d, 0xf0, 0xc6,
	0x49, 0x14, 0xa6, 0xde, 0x64, 0x21, 0x45, 0x51, 0x9f, 0x2e, 0x48, 0xae, 0xc0, 0xd2, 0x74, 0x78,
	0xfd, 0xb2, 0x34, 0x7f, 0xe1, 0xfa, 0xd5, 0x76, 0x56, 0xd3, 0x2c, 0x4d, 0x67, 0xf9, 0xdd, 0x8c,
	0x01, 0x6d, 0x17, 0x0e, 0x7f, 0x03, 0x07, 0xf3, 0x84, 0xc6, 0x81, 0x3d, 0xa3, 0x22, 0xf0, 0x6c,
	0x96, 0x32, 0xfe, 0x1e, 0xca, 0xe9, 0x22, 0x12, 0x4f, 0xce, 0x85, 0xd6, 0x61, 0xa7, 0xd1, 0x96,
	0x36, 0x5a, 0x68, 0xb8, 0x88, 0x28, 0x61, 0x3c, 0x7e, 0x01, 0x15, 0xd6, 0x5d, 0x96, 0x6b, 0xa7,
	0x36, 0xaf, 0x50, 0x8d, 0x1c, 0x30, 0xa0, 0x6b, 0xa7, 0x76, 0xf3, 0x9f, 0x25, 0x10, 0xbf, 0x56,
	0x2d, 0xfc, 0x03, 0xec, 0x4e, 0x63, 0xdb, 0x0b, 0x78, 0xe4, 0xad, 0xba, 0x7e, 0x64, 0x44, 0xa1,
	0x4e, 0x32, 0x3d, 0xfc, 0x13, 0x54, 0xef, 0x67, 0xb6, 0x63, 0xc5, 0x5e, 0x44, 0x67, 0x2e, 0xef,
	0xa7, 0x6a, 0xe7, 0x6c, 0xdd, 0xec, 0x6a, 0x66, 0x3b, 0x84, 0xb3, 0x4b, 0x5b, 0xb8, 0x5f, 0x62,
	0xcd, 0x9f, 0x36, 0xb2, 0xd9, 0x88, 0x81, 0xbf, 0x83, 0x3a, 0x2d, 0xda, 0xdf, 0x62, 0xd7, 0xcf,
	0xba, 0xbd, 0x46, 0x6a, 0x4b, 0xb0, 0x4f, 0x17, 0xcd, 0xb7, 0xf0, 0xea, 0x77, 0xa3, 0x61, 0x0c,
	0x3b, 0x2c, 0x5e, 0x6e, 0xcc, 0xbf, 0x9b, 0x73, 0x38, 0xda, 0x6a, 0x36, 0xfc, 0x16, 0x20, 0x9a,
	0x8f, 0x7d, 0xcf, 0xc9, 0x23, 0xb1, 0x83, 0x9c, 0xac, 0xb5, 0xa4, 0xc1, 0x49, 0x56, 0xeb, 0x4a,
	0x54, 0x7c, 0xe2, 0x37, 0x00, 0xa1, 0xef, 0x16, 0x7d, 0x9c, 0x9d, 0xfe, 0x70, 0xcd, 0x48, 0xf7,
	0x5d, 0x52, 0x09, 0x7d, 0x37, 0x93, 0x9a, 0xef, 0xa0, 0xf1, 0x88, 0x43, 0xfc, 0x6a, 0x2b, 0x34,
	0xcb, 0x73, 0x15, 0xa4, 0xe9, 0x42, 0x7d, 0xc3, 0x23, 0xfe, 0xc3, 0xe6, 0xf8, 0x64, 0x06, 0xeb,
	0xc3, 0xd2, 0x81, 0xa7, 0x6b, 0x0a, 0x56, 0xe2, 0x4d, 0x03, 0x3b, 0x9d, 0xc7, 0x94, 0x77, 0x4e,
	0x8d, 0x34, 0x56, 0xaa, 0x66, 0x41, 0x35, 0x7f, 0x13, 0x00, 0x56, 0xd3, 0x84, 0x5f, 0x03, 0x38,
	0xd1, 0xdc, 0x9a, 0xd8, 0x33, 0xcf, 0xcf, 0x72, 0x3a, 0xec, 0x40, 0x5b, 0x8e, 0xe6, 0x3d, 0x8e,
	0x90, 0x8a, 0x53, 0x7c, 0xb2, 0x74, 0x98, 0x6a, 0x32, 0x1f, 0xa7, 0x8b, 0x88, 0xf2, 0x5b, 0xa8,
	0x13, 0x66, 0x6d, 0x66, 0x08, 0x3e, 0x85, 0x7d, 0xa6, 0x40, 0x7f, 0x4d, 0x79, 0x37, 0xd6, 0xc9,
	0x9e, 0x13, 0xcd, 0x95, 0x5f, 0x53, 0xfc, 0x12, 0x76, 0xc7, 0xb1, 0x1d, 0xb8, 0x7c, 0x03, 0x1c,
	0x76, 0xf6, 0xda, 0x97, 0x4c, 0x22, 0x19, 0xc8, 0xfc, 0xf2, 0x0f, 0x6b, 0xe2, 0xdb, 0xd3, 0x44,
	0xec, 0x64, 0x7e, 0x39, 0xd4, 0x63, 0x08, 0x6e, 0x80, 0x10, 0x26, 0xe2, 0x07, 0x9e, 0x5b, 0xb9,
	0xad, 0x27, 0x44, 0x08, 0x13, 0x76, 0x99, 0x61, 0x62, 0xe5, 0x03, 0xcc, 0xe7, 0xb9, 0x4e, 0x2a,
	0x61, 0xf2, 0x29, 0x03, 0xf0, 0x53, 0xd8, 0x0b, 0x13, 0x9e, 0x8a, 0xc1, 0xa9, 0xdd, 0x30, 0x61,
	0x99, 0xfc, 0x0d, 0x9e, 0xaf, 0xad, 0x97, 0x78, 0xc6, 0x27, 0xaa, 0x58, 0x0a, 0xbf, 0xf0, 0x31,
	0x3c, 0x5d, 0xed, 0x97, 0x9c, 0xcf, 0xd7, 0xc3, 0x0b, 0xa8, 0xb8, 0xf4, 0xb3, 0xe7, 0x50, 0xcb,
	0x73, 0x45, 0x37, 0x1b, 0xd9, 0x0c, 0x50, 0xdd, 0xe6, 0xbf, 0x4b, 0x80, 0xb6, 0xb7, 0x05, 0x16,
	0x61, 0xbf, 0x48, 0xb0, 0x74, 0x2e, 0xb4, 0xea, 0xa4, 0x10, 0xf1, 0x33, 0xd8, 0x73, 0xe9, 0x67,
	0xd6, 0x06, 0x02, 0x2f, 0x55, 0x2e, 0xe1, 0x97, 0x50, 0x59, 0x55, 0xb1, 0x9c, 0x75, 0xc8, 0x12,
	0x60, 0x2c, 0xdb, 0x11, 0xf6, 0x94, 0x06, 0xa9, 0xb8, 0x73, 0x2e, 0xb4, 0x2a, 0x64, 0x05, 0xb0,
	0x31, 0x72, 0x6c, 0xdf, 0x1f, 0xdb, 0xce, 0x83, 0x75, 0x6f, 0x27, 0xf7, 0xe2, 0x6e, 0x36, 0x46,
	0x05, 0x78, 0x65, 0x27, 0xf7, 0xcd, 0x29, 0xc0, 0x6a, 0x49, 0xb1, 0x04, 0x7d, 0x6f, 0xe6, 0xa5,
	0xd4, 0x15, 0x4b, 0xe7, 0xa5, 0xd6, 0x01, 0x29, 0x44, 0xfc, 0x1d, 0x08, 0x93, 0xb1, 0x28, 0xf0,
	0x4e, 0x6f, 0xac, 0xed, 0xb5, 0x9e, 0xed, 0xd0, 0x71, 0x18, 0x3e, 0x10, 0x61, 0x32, 0x66, 0x3b,
	0xcc, 0xb7, 0x83, 0xe9, 0xdc, 0x9e, 0xb2, 0x64, 0xf9, 0x85, 0x14, 0x72, 0xf3, 0x2d, 0xe0, 0x2f,
	0xad, 0x58, 0xd5, 0x66, 0xb6, 0x73, 0xef, 0x05, 0xfc, 0x12, 0x4b, 0xdc, 0xa6, 0x92, 0x23, 0xaa,
	0xdb, 0xfc, 0xad, 0x0c, 0x15, 0xc9, 0xb8, 0xa1, 0xbe, 0x13, 0xce, 0x28, 0x7e, 0x03, 0xd8, 0xb1,
	0x83, 0x30, 0xf0, 0x1c, 0xdb, 0xb7, 0xd6, 0x96, 0x25, 0x3b, 0xf7, 0xf1, 0x92, 0x19, 0x15, 0x5b,
	0x53, 0x82, 0x67, 0xc5, 0xc3, 0xc7, 0xda, 0xd1, 0xf2, 0xc3, 0xe9, 0x94, 0xba, 0x96, 0x17, 0xe4,
	0x8b, 0xb4, 0x56, 0x3c, 0x7f, 0x7c, 0x83, 0x36, 0xec, 0x95, 0x30, 0xe0, 0x9a, 0x6a, 0x80, 0x55,
	0xf8, 0x66, 0xed, 0xd5, 0xdd, 0x76, 0xf3, 0xfc, 0x11, 0x37, 0xa7, 0x6b, 0xfa, 0x1b, 0xae, 0x6e,
	0xe1, 0x2c, 0xa6, 0xf3, 0xc4, 0x1e, 0xfb, 0xd4, 0xe2, 0x5b, 0x7a, 0xdb, 0xb1, 0x78, 0xf6, 0xf5,
	0xf5, 0xfe, 0xa2, 0x30, 0x65, 0x9c, 0xbc, 0x19, 0x81, 0xf5, 0xf0, 0x57, 0x3d, 0x8b, 0x2d, 0x5e,
	0xf3, 0xd3, 0xaf, 0xd8, 0xb3, 0xfb, 0xf7, 0x27, 0x89, 0x95, 0x50, 0x27, 0xa6, 0x29, 0x1f, 0xb5,
	0x1a, 0xa9, 0xf8, 0x93, 0xc4, 0xe4, 0x00, 0xfe, 0x01, 0x6a, 0xc5, 0x15, 0xf2, 0x77, 0xed, 0x03,
	0xaf, 0xff, 0xf2, 0xc4, 0xfc, 0x61, 0xab, 0xda, 0x2b, 0x01, 0xff, 0x91, 0xb7, 0x49, 0x2f, 0xdf,
	0xa2, 0x6b, 0x6a, 0xeb, 0x7d, 0xd2, 0x0c, 0xa0, 0xba, 0x46, 0xe1, 0x37, 0xb0, 0x9f, 0xcf, 0x09,
	0xef, 0x00, 0xd6, 0x60, 0x6b, 0xb4, 0x99, 0x51, 0xa4, 0xd0, 0xc1, 0x3f, 0xc2, 0xc1, 0x24, 0xf7,
	0x96, 0x37, 0xe4, 0xe3, 0x91, 0x96, 0x5a, 0xcd, 0x13, 0xc0, 0x5f, 0x3a, 0x6c, 0xde, 0x40, 0xe3,
	0x11, 0x33, 0xfc, 0x2d, 0x3f, 0x33, 0x4d, 0x12, 0x2b, 0x0d, 0x1f, 0x68, 0x90, 0x37, 0x65, 0x35,
	0xc3, 0x86, 0x0c, 0xda, 0xea, 0x5a, 0x61, 0xab, 0x6b, 0x2f, 0xfe, 0x5b, 0x02, 0xfc, 0x65, 0x11,
	0xf1, 0x4b, 0x10, 0xa5, 0xd1, 0xf0, 0x4a, 0xd1, 0x86, 0xaa, 0x2c, 0x0d, 0x55, 0x5d, 0xb3, 0x46,
	0xa6, 0x42, 0x2c, 0x43, 0x32, 0x4d, 0xf4, 0x04, 0xbf, 0x81, 0xd7, 0x5b, 0xac, 0x39, 0xd4, 0x89,
	0xd2, 0xb5, 0x4c, 0x43, 0x1f, 0xaa, 0xbd, 0x3b, 0x4b, 0x26, 0x4a, 0x97, 0xb1, 0xd2, 0xc0, 0x44,
	0x25, 0xdc, 0x86, 0x8b, 0xc7, 0xd5, 0x7b, 0x92, 0xac, 0x5c, 0xea, 0x7a, 0x7f, 0x43, 0x5f, 0xc0,
	0xe7, 0xf0, 0x72, 0x5b, 0x3f, 0xf7, 0x3b, 0xd4, 0xfb, 0x8a, 0x86, 0xca, 0xf8, 0x5b, 0x78, 0xb5,
	0xa5, 0xb1, 0x74, 0x95, 0xa9, 0xec, 0x5c, 0xdc, 0xc1, 0xd1, 0xd6, 0x3f, 0x46, 0xdc, 0x84, 0x33,
	0x49, 0x96, 0xf5, 0x91, 0x36, 0x64, 0x01, 0x33, 0x3b, 0x69, 0x70, 0x23, 0xdd, 0x99, 0x96, 0x41,
	0xf4, 0x6b, 0x63, 0x88, 0x4a, 0xbf, 0xa7, 0xc3, 0x65, 0x05, 0x95, 0x2f, 0xfe, 0x55, 0x82, 0xca,
	0xf2, 0x95, 0xc1, 0x47, 0x50, 0x95, 0x8d, 0x91, 0x35, 0xd2, 0xfa, 0x9a, 0x7e, 0xa3, 0xa1, 0x27,
	0xb8, 0x0a, 0xfb, 0x0c, 0xb8, 0xfd, 0xeb, 0x7b, 0x54, 0xc2, 0x87, 0x00, 0xb9, 0x60, 0xbd, 0x7f,
	0x87, 0x84, 0x82, 0x34, 0x0c, 0x19, 0x95, 0x0b, 0xd2, 0x30, 0x64, 0x46, 0xee, 0x14, 0xa4, 0x44,
	0xae, 0xd1, 0x2e, 0xae, 0xc1, 0x01, 0x13, 0x54, 0xe9, 0xfd, 0x3b, 0xb4, 0x87, 0x01, 0xf6, 0x98,
	0x64, 0x5e, 0xa1, 0xfd, 0x82, 0xb9, 0x56, 0x0d, 0x13, 0x1d, 0x60, 0x04, 0x35, 0x26, 0x5d, 0x0e,
	0x24, 0xb9, 0xdf, 0x53, 0x35, 0x54, 0xb9, 0xe8, 0xc3, 0x2e, 0x7f, 0xa4, 0x70, 0x03, 0x8e, 0x2e,
	0x89, 0xa4, 0x75, 0xad, 0x91, 0xc6, 0x7f, 0x95, 0x2e, 0x7a, 0x82, 0xeb, 0x50, 0xc9, 0x40, 0x55,
	0xfb, 0x19, 0x95, 0x56, 0xe2, 0xd5, 0x50, 0x46, 0x02, 0x3b, 0x4d, 0x26, 0x6a, 0x7a, 0x5f, 0x95,
	0x50, 0xf9, 0xe2, 0x3f, 0x02, 0x08, 0x7a, 0xc2, 0x52, 0xd5, 0xcd, 0xb5, 0x43, 0x66, 0xf2, 0x8d,
	0xaa, 0x75, 0xf5, 0x1b, 0x56, 0x63, 0x80, 0x3d, 0xdd, 0xb4, 0x74, 0xf3, 0x16, 0x09, 0xcc, 0xa5,
	0x6e, 0x5a, 0xaa, 0x71, 0xa5, 0x6b, 0x0a, 0x2a, 0xe7, 0x94, 0xf9, 0xfe, 0x47, 0xb4, 0xc3, 0x52,
	0xd7, 0x4d, 0x6b, 0xa0, 0x6a, 0xa3, 0x5b, 0xb4, 0x8b, 0x8f, 0xa1, 0xbe, 0x72, 0x62, 0xc9, 0x0a,
	0xda, 0xcb, 0xfd, 0x4a, 0x5a, 0x97, 0xe8, 0x6a, 0x17, 0xed, 0xb3, 0x2b, 0xd1, 0x4d, 0xcb, 0x90,
	0x06, 0xd7, 0xe8, 0x20, 0x27, 0x7b, 0x44, 0x51, 0x2e, 0xcd, 0x2e, 0xaa, 0xe4, 0xf6, 0xfc, 0xe4,
	0x97, 0x0a, 0x21, 0x77, 0x08, 0xf2, 0x00, 0xa6, 0xae, 0xe9, 0x26, 0xaa, 0xb2, 0xd3, 0xb0, 0x70,
	0xfa, 0x47, 0x75, 0xa8, 0xc8, 0x57, 0xa8, 0x96, 0xe7, 0x72, 0x63, 0xfc, 0x05, 0xd5, 0x73, 0x55,
	0x5d, 0xeb, 0xdf, 0xe9, 0xe8, 0x30, 0xf7, 0x6d, 0x5c, 0xa9, 0x03, 0x76, 0xad, 0x47, 0xb8, 0x02,
	0xbb, 0x4c, 0xb3, 0x8b, 0x50, 0xae, 0xf8, 0x49, 0x1f, 0x7c, 0xd2, 0xd1, 0x71, 0x9e, 0xd1, 0x50,
	0xfd, 0xa4, 0x23, 0x9c, 0x0b, 0xd2, 0x8d, 0x7e, 0x8b, 0x1a, 0xb9, 0xde, 0xb5, 0xa2, 0x7c, 0xd4,
	0xd1, 0x49, 0x7e, 0x0b, 0x3f, 0x6b, 0xb7, 0xda, 0x50, 0x47, 0x4f, 0xf3, 0xc8, 0x97, 0xb2, 0x8e,
	0x9e, 0x5d, 0xb4, 0x96, 0x3b, 0x85, 0x0f, 0x5b, 0x15, 0xf6, 0xf3, 0x39, 0x47, 0x4f, 0x98, 0x93,
	0x62, 0xbc, 0x51, 0xe9, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xa7, 0x3d, 0x24, 0x83, 0x0d,
	0x00, 0x00,
}
